train:
  dataset:
    type@: FlowerDataset
    img1_dir: /home/wzliu/lzq/data/flower/1_1
    img2_dir: /home/wzliu/lzq/data/flower/0_0
    sf: 4
    img1_keys: ['SR_EDSR_baseline']
    img2_keys: []
    names_path: /home/wzliu/lzq/data/flower/train.txt
    landmark: /home/wzliu/lzq/data/flower/landmark/0_0_1_1
    landmark_reverse: True
  loader:
    batch_size: 2
    shuffle: True
  
test:
  dataset:
    type@: FlowerDataset
    img1_dir: /home/wzliu/lzq/data/flower/1_1
    img2_dir: /home/wzliu/lzq/data/flower/0_0
    sf: 4
    img1_keys: ['SR_EDSR_baseline']
    img2_keys: []
    names_path: /home/wzliu/lzq/data/flower/test.txt
    landmark: /home/wzliu/lzq/data/flower/landmark/0_0_1_1
    landmark_reverse: True
  loader:
    batch_size: 1
    shuffle: False
  
module:
  type@: EnhancedCrossNetModule
  optimizer:
    type@: Adam
    lr: 0.0001
    weight_decay: 0.00005
  input_mode:
    input: SR_EDSR_baseline
  loss_config:
    weight:
      reconstruct: 1
      landmark: 1
    reduce: batch
engine:
  max_epochs: 50
  mnt_metric: val_psnr
  mnt_mode: max
  log_img_step: 500
  valid_log_img_step: 50
  pbar: qqdm
  ckpt_save_mode: latest_1
  enable_tensorboard: False